sudo: required
language: generic

services:
  - docker

script:
  - docker build . --tag marcosomma_web:latest

deploy:
  provider: elasticbeanstalk
  region: 'eu-south-1'
  app: 'marcosomma.github.io-prod'
  env: 'Marcosommagithubioprod-env'
  bucket_name: 'elasticbeanstalk-eu-south-1-496050274871'
  bucket_path: 'marcosomma.github.io-prod'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
