sudo: required
language: generic

services:
  - docker

before_install:
  - docker build . --tag marcosomma_web:latest

script:
  - docker run -e CI=true marcosomma_web:latest npm run build

deploy:
  provider: elasticbeanstalk
  region: 'eu-south-1'
  app: 'marcosomma.github.io'
  env: 'Marcosommagithubio-env'
  bucket_name: 'elasticbeanstalk-eu-south-1-496050274871'
  bucket_path: 'marcosomma.github.io'
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
